name: 'SendPlayerToFallback'
main: fr.hysoria.sendplayertofallback.Main
version: '1.0V'
description: 'Send player to the callback server with a command'
author: 'Clem_Fern'
website: 'https://hysoria.eu/'
commands:
 playertofallback:
  description: "command to send player on the fallback server"